# Generated by Django 5.2 on 2025-04-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cna'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cna',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='cna',
            name='is_available',
        ),
        migrations.AddField(
            model_name='cna',
            name='experience',
            field=models.TextField(default='Experience not provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cna',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cna',
            name='location',
            field=models.CharField(default={}, max_length=100),
            preserve_default=False,
        ),
    ]
