# Generated by Django 5.2 on 2025-04-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cna_hire_date_remove_cna_is_available_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CNAProfile',
        ),
    ]
