# Generated by Django 5.2 on 2025-04-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNAListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('availability', models.TextField()),
            ],
        ),
    ]
