# Generated by Django 5.2 on 2025-04-29 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cnalisting_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyJobSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('week_of', models.DateField(help_text='Start date of the week (e.g., Monday)')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pay_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
